#include"../framework/test_framework.h"
#include"../../include/math_utils.h"
#include"../testConstants.h"

static void test_M_Min(void) {
    TEST_ASSERT_EQ(M_Min(INT_MIN, INT_MAX), INT_MIN, "M_Min of INT_MIN and INT_MAX");
    TEST_ASSERT_EQ(M_Min(INT8_MAX_VAL, INT8_MIN_VAL), INT8_MIN_VAL, "M_Min of INT8_MAX_VAL and INT8_MIN_VAL");
    TEST_ASSERT_EQ(M_Min(INT16_MAX_VAL, INT16_MIN_VAL), INT16_MIN_VAL, "M_Min of INT16_MAX_VAL and INT16_MIN_VAL");
    TEST_ASSERT_EQ(M_Min(INT32_MAX_VAL, INT32_MIN_VAL), INT32_MIN_VAL, "M_Min of INT32_MAX_VAL and INT32_MIN_VAL");
    TEST_ASSERT_EQ(M_Min(INT64_MAX_VAL, INT64_MIN_VAL), INT64_MIN_VAL, "M_Min of INT64_MAX_VAL and INT64_MIN_VAL");
    TEST_ASSERT_EQ(M_Min(UINT_MAX_VAL, UINT_MIN_VAL), UINT_MIN_VAL, "M_Min of UINT_MAX_VAL and UINT_MIN_VAL");
    TEST_ASSERT_EQ(M_Min(UINT8_MAX_VAL, UINT8_MIN_VAL), UINT8_MIN_VAL, "M_Min of UINT8_MAX_VAL and UINT8_MIN_VAL");
    TEST_ASSERT_EQ(M_Min(UINT16_MAX_VAL, UINT16_MIN_VAL), UINT16_MIN_VAL, "M_Min of UINT16_MAX_VAL and UINT16_MIN_VAL");        
    TEST_ASSERT_EQ(M_Min(UINT32_MAX_VAL, UINT32_MIN_VAL), UINT32_MIN_VAL, "M_Min of UINT32_MAX_VAL and UINT32_MIN_VAL");
    TEST_ASSERT_EQ(M_Min(UINT64_MAX_VAL, UINT64_MIN_VAL), UINT64_MIN_VAL, "M_Min of UINT64_MAX_VAL and UINT64_MIN_VAL");
    TEST_ASSERT_EQ(M_Min(FLOAT32_MAX_VAL, FLOAT32_MIN_VAL), FLOAT32_MIN_VAL, "M_Min of FLOAT32_MAX_VAL and FLOAT32_MIN_VAL");
    TEST_ASSERT_EQ(M_Min(FLOAT64_MIN_VAL, FLOAT64_MAX_VAL), FLOAT64_MIN_VAL, "M_Min of FLOAT64_MIN_VAL and FLOAT64_MAX_VAL");
}

static void test_M_Max(void) {
    TEST_ASSERT_EQ(M_Max(INT_MIN, INT_MAX), INT_MAX, "M_Max of INT_MIN and INT_MAX");
    TEST_ASSERT_EQ(M_Max(INT8_MAX_VAL, INT8_MIN_VAL), INT8_MAX_VAL, "M_Max of INT8_MAX_VAL and INT8_MIN_VAL");
    TEST_ASSERT_EQ(M_Max(INT16_MAX_VAL, INT16_MIN_VAL), INT16_MAX_VAL, "M_Max of INT16_MAX_VAL and INT16_MIN_VAL");
    TEST_ASSERT_EQ(M_Max(INT32_MAX_VAL, INT32_MIN_VAL), INT32_MAX_VAL, "M_Max of INT32_MAX_VAL and INT32_MIN_VAL");
    TEST_ASSERT_EQ(M_Max(INT64_MAX_VAL, INT64_MIN_VAL), INT64_MAX_VAL, "M_Max of INT64_MAX_VAL and INT64_MIN_VAL");
    TEST_ASSERT_EQ(M_Max(UINT_MAX_VAL, UINT_MIN_VAL), UINT_MAX_VAL, "M_Max of UINT_MAX_VAL and UINT_MIN_VAL");
    TEST_ASSERT_EQ(M_Max(UINT8_MAX_VAL, UINT8_MIN_VAL), UINT8_MAX_VAL, "M_Max of UINT8_MAX_VAL and UINT8_MIN_VAL");
    TEST_ASSERT_EQ(M_Max(UINT16_MAX_VAL, UINT16_MIN_VAL), UINT16_MAX_VAL, "M_Max of UINT16_MAX_VAL and UINT16_MIN_VAL");        
    TEST_ASSERT_EQ(M_Max(UINT32_MAX_VAL, UINT32_MIN_VAL), UINT32_MAX_VAL, "M_Max of UINT32_MAX_VAL and UINT32_MIN_VAL");
    TEST_ASSERT_EQ(M_Max(UINT64_MAX_VAL, UINT64_MIN_VAL), UINT64_MAX_VAL, "M_Max of UINT64_MAX_VAL and UINT64_MIN_VAL");
    TEST_ASSERT_EQ(M_Max(FLOAT32_MAX_VAL, FLOAT32_MIN_VAL), FLOAT32_MAX_VAL, "M_Max of FLOAT32_MAX_VAL and FLOAT32_MIN_VAL");
    TEST_ASSERT_EQ(M_Max(FLOAT64_MIN_VAL, FLOAT64_MAX_VAL), FLOAT64_MAX_VAL, "M_Max of FLOAT64_MIN_VAL and FLOAT64_MAX_VAL");
}

void run_math_utils_tests(void) {
}