name: ClusterFuzzLite

on: 
  push:
    branches:
      - pratiksha
  pull_request:
    branches:
      - pratiksha

permissions: read-all

jobs:
  cflite:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Fuzzers
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sanitizer: 'address'
          language: 'c'

      - name: Run Fuzzers
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 600
          mode: 'code-change'
          sanitizer: 'address'
          language: 'c' 